[fix] headless service FQDN define.
taosdata/TDengine-Operator pull request #2
Opened 2021-07-14 08:55 UTC by kii-la

2021-07-14 12:12 UTC, zitsen requested changes
We use angular convential changelog as commit message style - for changelog auto generation, in this project :D.

See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular

2021-07-15 05:36 UTC, kii-la commented on helm/tdengine/templates/statefulset.yaml
> +            value: {{ .Release.Name }}
if `STS_NAME: {{ include "tdengine.fullname" . }}` 

```yaml
          - name: TAOS_FIRST_EP
            value: "$(STS_NAME)-0.$(SERVICE_NAME).$(STS_NAMESPACE).svc.cluster.local:$(TAOS_SERVER_PORT)"
```

Is it correct to use `STS_NAME`  in this place?

2021-07-15 05:43 UTC, kii-la commented on helm/tdengine/templates/service.yaml
> +  name: {{ include "tdengine.fullname" . }}-headless
Usually, the default service is the Loadbalancer, and headless is the declaration that points to the corresponding Pod for statefulsets.

2021-07-15 05:53 UTC, kii-la commented on helm/tdengine/templates/service.yaml
> +  name: {{ include "tdengine.fullname" . }}-headless
and after testing, the headless service FQDN does not work without an additional service.

2021-07-15 07:13 UTC, zitsen commented on helm/tdengine/templates/statefulset.yaml
> +            value: {{ .Release.Name }}
Test it with `helm install ` with a different release name such as `taosd`

2021-07-15 07:15 UTC, zitsen commented on helm/tdengine/templates/service.yaml
> +  name: {{ include "tdengine.fullname" . }}-headless
The helm package is tested multiple times in rke2/minikube, I don't know what the `FQDN does not work` meaning, could you give me an test pipeline ?

2021-07-17 06:26 UTC, kii-la commented on helm/tdengine/templates/statefulset.yaml
> +            value: {{ .Release.Name }}
Yes, you're right. 
`STS_NAME` means the name of the stateful set, which should match the field in the stateful set metadata.

2021-07-18 05:42 UTC, kii-la commented on helm/tdengine/templates/statefulset.yaml
> +            value: {{ .Release.Name }}
Ok, I'm trying to finish preparing the new test environment, which was previously having the problem with a cluster built on RKE. I'm going to re-implement it here using kubeadmin.

2021-07-18 05:42 UTC, kii-la commented on helm/tdengine/templates/service.yaml
> +  name: {{ include "tdengine.fullname" . }}-headless
Ok, I'm trying to finish preparing the new test environment, which was previously having the problem with a cluster built on RKE. I'm going to re-implement it here using kubeadmin.

2021-07-18 09:55 UTC, zitsen commented
If you test it ok, could you re-request review?

2021-07-18 14:58 UTC, closed without merging